parameters:
  dynamic_domain_config.mapping: []

services:
    domain.config.resolver:
      public: true
      class: DynamicDomainConfig\Service\DomainConfigResolver
      arguments: ['%dynamic_domain_config_mapping%']

